{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fa85fbc6-1d36-4e7c-9871-93d6e65651bf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "from PIL import Image\n",
    "\n",
    "import numpy as np\n",
    " \n",
    "def load_image(image_path):\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "        Đọc ảnh từ đường dẫn cho trước và trả về đối tượng ảnh\n",
    "\n",
    "        Args: image_path\n",
    "\n",
    "        Returns: đối tượng hình ảnh\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "    try:\n",
    "\n",
    "        img = Image.open(image_path)\n",
    "\n",
    "        return img\n",
    "\n",
    "    except Exception as e:\n",
    "\n",
    "        print(\"Lỗi khi đọc hình ảnh từ: \", image_path, \" \", e)\n",
    "\n",
    "        return None\n",
    " \n",
    "def is_image_file(file_path):\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "        return: True - nếu là ảnh\n",
    "\n",
    "                False - nếu khác ảnh\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "    extensions =(\".jpg\", \".jpeg\", \".png\", \".gif\", \".bmp\")\n",
    "\n",
    "    return file_path.lower().endswith(extensions);\n",
    " \n",
    " \n",
    "def get_image_list(folder_path):\n",
    "\n",
    "    image_list = []\n",
    "\n",
    "    if os.path.exists(folder_path) and os.path.isdir(folder_path):\n",
    "\n",
    "        filenames = os.listdir(folder_path)\n",
    "\n",
    "        for filename in filenames:\n",
    "\n",
    "            file_path=os.path.join(folder_path, filename)\n",
    "\n",
    "            if  os.path.isfile(file_path) and is_image_file(file_path):\n",
    "\n",
    "                img = load_image(file_path)\n",
    "\n",
    "                image_list.append(img)\n",
    "\n",
    "    return image_list\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "84a04803-f989-4ac5-ba56-689dd114cbaf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "60afef9a-c919-4dea-ad74-a07e0aa8dc84",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
